// <auto-generated />
using System;
using EventBoardBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EventBoardBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250911124848_nullableOff")]
    partial class nullableOff
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventBoardBackend.Data.Models.Entities.CompanyModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("EventBoardBackend.Data.Models.Entities.ManagerModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("EventBoardBackend.Data.Models.Entities.StudentModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("EventBoardBackend.Data.Models.Entities.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .HasColumnType("text");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EventBoardBackend.Models.Entities.MeetingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("ManagerId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("MeetingDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("MeetingModelStudentModel", b =>
                {
                    b.Property<int>("AttendedMeetingsId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentsId")
                        .HasColumnType("integer");

                    b.HasKey("AttendedMeetingsId", "StudentsId");

                    b.HasIndex("StudentsId");

                    b.ToTable("MeetingModelStudentModel");
                });

            modelBuilder.Entity("EventBoardBackend.Data.Models.Entities.ManagerModel", b =>
                {
                    b.HasOne("EventBoardBackend.Data.Models.Entities.CompanyModel", "Company")
                        .WithMany("Managers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventBoardBackend.Data.Models.Entities.UserModel", "User")
                        .WithOne("Manager")
                        .HasForeignKey("EventBoardBackend.Data.Models.Entities.ManagerModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventBoardBackend.Data.Models.Entities.StudentModel", b =>
                {
                    b.HasOne("EventBoardBackend.Data.Models.Entities.UserModel", "User")
                        .WithOne("Student")
                        .HasForeignKey("EventBoardBackend.Data.Models.Entities.StudentModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventBoardBackend.Models.Entities.MeetingModel", b =>
                {
                    b.HasOne("EventBoardBackend.Data.Models.Entities.ManagerModel", "Manager")
                        .WithMany("ManagedMeetings")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("MeetingModelStudentModel", b =>
                {
                    b.HasOne("EventBoardBackend.Models.Entities.MeetingModel", null)
                        .WithMany()
                        .HasForeignKey("AttendedMeetingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventBoardBackend.Data.Models.Entities.StudentModel", null)
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventBoardBackend.Data.Models.Entities.CompanyModel", b =>
                {
                    b.Navigation("Managers");
                });

            modelBuilder.Entity("EventBoardBackend.Data.Models.Entities.ManagerModel", b =>
                {
                    b.Navigation("ManagedMeetings");
                });

            modelBuilder.Entity("EventBoardBackend.Data.Models.Entities.UserModel", b =>
                {
                    b.Navigation("Manager");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
